version: "2"
linters:
  enable:
    - revive
    - whitespace
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gofumpt
    - goimports
